export const letters = [
  "A",
  "B",
  "C",
  "Ç",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
]

export const handConfigs = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8a",
  "8b",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18a",
  // "18b",
  "19",
  "20",
  "21",
  "22a",
  "22b",
  // "23",
  "24",
  "25",
  // "26",
  // "27",
  // "28",
  // "29a",
  // "29b",
  // "30",
  // "31",
  "32",
  // "33",
  // "34",
  // "35a",
  // "35b",
  // "36",
  // "37a",
  // "37b",
  "38",
  "39",
  "40",
  // "41",
  "42",
  // "43",
  // "44",
  // "45",
  // "46a",
  // "46b",
  // "47",
  // "48",
  // "49",
  // "50",
  "51a",
  // "51b",
  // "52",
  // "53a",
  // "53b",
  "54",
  // "55",
  "56",
  // "57",
  // "58",
  "59a",
  // "59b",
  // "60",
  "61",
  // "62",
  // "63",
  // "64",
]

export const categories = [
    "Cidade",
    "Município",
    "Cidade do Sudeste",
    "Município do Sudeste",
    "Cidade Mineira",
    "Município Mineiro",
    "Cidade Fluminense",
    "Município Fluminense",
    "Capital",
    "Cidade Capixaba",
    "Município Capixaba",
    "Cidade Paulista",
    "Município Paulista",
    "Cidade Gaúcha",
    "Município Gaúcho",
    "Cidade Catarinense",
    "Município Catarinense",
    "Cidade Paranaense",
    "Município Paranaense",
    "Cidade Goiana",
    "Município Goiano",
    "Cidade Sul-mato-grossense",
    "Município Sul-mato-grossense",
    "Cidade Mato-grossense",
    "Município Mato-grossense",
    "Cidade do Sul",
    "Município do Sul",
    "Cidade do Centro-Oeste",
    "Município do Centro-Oeste",
    "Cidade do Norte",
    "Município do Norte",
    "Cidade Amazonense",
    "Município Amazonense",
    "Cidade Acreana",
    "Município Acreano",
    "Estado (to do)",
    "Cidade Roraimense",
    "Município Roraimense",
    "Cidade Amapaense",
    "Município Amapaense",
    "Cidade Paraense",
    "Município Paraense",
    "Cidade Tocantinense",
    "Município Tocantinense",
    "Cidade Rondonense",
    "Município Rondonense",
    "Cidade do Nordeste",
    "Município do Nordeste",
    "Cidade Baiana",
    "Município Baiano",
    "Cidade Sergipana",
    "Município Segipano",
    "Cidade Alagoana",
    "Município Alagoano",
    "Cidade Pernambucana",
    "Município Pernambucano",
    "Cidade Paraibana",
    "Município Paraibano",
    "Cidade Potiguar",
    "Município Portiguar",
    "Cidade Cearense",
    "Município Cearense",
    "Cidade Piauiense",
    "Município Piauiense",
    "Cidade Maranhense",
    "Município Maranhense",
    "Química",
    "Disciplina",
    "Ciência",
    "Área do conhecimento",
    "Física",
    "Educação",
    "Ciências Biológicas",
    "Biologia",
    "Matemática",
    "Medicina",
    "Saúde",
]